"""remove roles

Revision ID: 00629fbaa650
Revises: 7a5d7a0dab1c
Create Date: 2018-04-23 10:41:35.307053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00629fbaa650'
down_revision = '7a5d7a0dab1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
