"""add time

Revision ID: 75bfad47d534
Revises: f632241d1f1f
Create Date: 2018-04-20 14:25:36.123993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bfad47d534'
down_revision = 'f632241d1f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timeposted', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_timeposted'), 'posts', ['timeposted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timeposted'), table_name='posts')
    op.drop_column('posts', 'timeposted')
    # ### end Alembic commands ###
