"""add image

Revision ID: 7a5d7a0dab1c
Revises: df12d4c0fbae
Create Date: 2018-04-22 18:09:10.556811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5d7a0dab1c'
down_revision = 'df12d4c0fbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_name', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'image_name')
    # ### end Alembic commands ###
